### ISSUE TITLE
Issue on page /unsolved_problems/PS1/PS1.html

### ISSUE THREAD

**Issue by adrulpz** [angadhn/SpacecraftDynamics#27]
Hi Angadh, just a couple of observations on this set.  

Q1: **N** and **E** could be in bold letters. The last two expressions still have the "$" symbol and is missing a space just before "and".
Q2: same problem, **v** still have the "$" symbol
Q3:  same problem with the acceleration expression
Q4: after "given by: "needs to be rewritten, there are no spaces, and it is all as a math expression

**Comment by angadhn** [comment]
great. How about making the changes? Top-level procedure and I think @Joosty can guide too):
1. fork the repo.
2. clone your fork.
3. create a branch called "PS1_Fix".
4. Make changes.
5. Commit and push changes to fork.
6. Open a PR.

Procedures are outlined in greater detail here: Flow

**Comment by Joosty** [comment]
Happy to help if you need to be ran through anything @adrulpz :) can hop on a call if you need!

**Comment by adrulpz** [comment]
Thanks, @Joosty. I appreciated it. I will make the changes later today. If I need help I will reach out :)
And @angadhn, I think you forgot the link 😅

**Comment by angadhn** [comment]
Fixed in [PR29](https://github.com/angadhn/SpacecraftDynamics/pull/29).
