### ISSUE TITLE
Issue on page /unsolved_problems/PS1/PS1.html

### ISSUE THREAD

**Issue by Warfxdes** [angadhn/SpacecraftDynamics#34]
# Title: Incorrect Angular Momentum Formula in Problem Set 1 Question 2
## Description: 
The problem incorrectly states the angular momentum as: h = r(dot) × v

## Solution
The correct formula should be: h = r × v

## Reason / Clarification: 
Angular momentum is defined as the cross product of the position vector r and the velocity vector v, not the derivative of the position vector.

![Screenshot 2024-10-03 223559](https://github.com/user-attachments/assets/5e45089e-46d3-4782-a790-a9bed016dbfa)

**Comment by Joosty** [comment]
You are correct, I will work on this small correction today and then open a pull request.

Cheers for pointing this out @Warfxdes !
