### ISSUE TITLE
Issue on page /orbital-mechanics/Lecture6/Lecture6.html

### ISSUE THREAD

**Issue by Warfxdes** [angadhn/SpacecraftDynamics#36]
### Description: 
There is an inconsistency between Equation 125 and Equation 154 (Both are equations for True Anomaly)

![Screenshot 2024-10-26 234939](https://github.com/user-attachments/assets/92b08764-847a-47d7-a9bf-c479077acd75)

However, in Equation 154, the signs inside the square root might be incorrect.

![Screenshot 2024-10-26 234757](https://github.com/user-attachments/assets/e0df3ab5-17d7-4067-b9c3-edbb7e977305)

This discrepancy changes the mathematical relationship, as the signs in the square root should be reversed in Equation 154 to match Equation 125. (Images have been added for your convinence)

### Recommendation: 
The issue could be solved by swapping the signs in the square root of Equation 154 to match Equation 125, or making Tan (theta/2) the subject.

![image](https://github.com/user-attachments/assets/d97ed43d-66e0-426b-a9ac-79b10add8e26)

**Comment by angadhn** [comment]
Yup- good spot.  Changed!
