### ISSUE TITLE
Issue on page /orbital-mechanics/Lecture2/Lecture2.html

### ISSUE THREAD

**Issue by samalj05** [angadhn/SpacecraftDynamics#37]
Equation 66 on Two Body Dynamics seems to be missing a minus sign on the second term, which contradicts with the handwritten notes. See images below:

![image](https://github.com/user-attachments/assets/3c047861-5050-4884-8bf8-4f78137b9f20)

![image](https://github.com/user-attachments/assets/806d1227-9df7-4742-aaaf-ab119e343fbb)

**Comment by angadhn** [comment]
Thanks! Fixed.
