### ISSUE TITLE
Issue on page /orbital-mechanics/Lecture7/Lecture7.html

### ISSUE THREAD

**Issue by AAcexofc** [angadhn/SpacecraftDynamics#38]
Minor typo in Orbital Maneuvers: Hohmann transfer.
Refer to the image, second line is missing an "="   [VB2=root(....)]

![Screenshot 2024-10-30 164102](https://github.com/user-attachments/assets/03eb47f8-e12e-49a2-ba03-25146fe42bf4)

**Comment by angadhn** [comment]
Brilliant thanks!
