### ISSUE TITLE
Issue on page /orbital-mechanics/Lecture2/Lecture2.html - Equation 35.

### ISSUE THREAD

**Issue by Leon04nb** [angadhn/SpacecraftDynamics#46]
Hi, I think there's an issue with Equation 35. The RHS denominator shows a vector in BOLD when it should be a scalar in italics. The current code is \bf{\dot v} = -\frac{\mu}{r^3}\bf{r}, where I think it should be \dot{\bf {v}} = -\frac{\mu}{r^3}\bf{r}.
![Two body dynamics equation](https://github.com/user-attachments/assets/3cc2b0ad-43ed-4417-8efe-4fb7418c5831).

Thanks, 
Leon

**Comment by angadhn** [comment]
Thanks, fixed.
