### ISSUE TITLE
Issue on page /orbital-mechanics/Lecture2/Lecture2.html

### ISSUE THREAD

**Issue by deniskbest** [angadhn/SpacecraftDynamics#61]
1. in equation 47 V-theta is in bold although it is a scalar.
2. also, in the following line:
"The first term on the RHS of the last of Equations 46 is zero because 
r and Vr 
are parallel; thus the second term is the only term remaining."
shouldn't it be 
"The first term on the RHS of the last of Equations 46 is zero because r and Er are parallel"? vr is a scalar quantity and I dont think it can be parallel to a vector quantity r.
3. in the line just before equation 53: R(vector)=r(scalar)*er(vector), r(scalar) is in bold although it is a scalar

**Comment by angadhn** [comment]
1. and 3. Fixed.
2. If $\bf r$ and ${\bf v}_r$ are parallel, then that implies that ${\bf e}_r$ is parallel to $\bf r$ as well.

Thanks for the comment!
